#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: $0 <url>"
    exit 1
fi
url=${1%.git}
if [[ $url =~ @([^:]*): ]]; then
  domain=${BASH_REMATCH[1]}
else
  domain=$(echo "$url" | sed -n 's|^.*//\([^/]*\)/.*|\1|p')
fi

if [[ $url =~ :([^/]*)/([^/]*)$ ]]; then
  user=${BASH_REMATCH[1]}
  repo=${BASH_REMATCH[2]}
else
  user_repo=$(echo "$url" | sed -n 's|^.*/\([^/]*\)/\([^/]*\)$|\1/\2|p')
  user=$(echo "$user_repo" | cut -d '/' -f 1)
  repo=$(echo "$user_repo" | cut -d '/' -f 2)
fi
path="$HOME/repos/$domain/$user/$repo"
path="$(echo "$path" | tr '[:upper:]' '[:lower:]')"
echo "Cloning $url to $path"
if [ -e "$path" ]; then
    echo "Path $path already exists"
    exit 1
fi
git clone "$url" "$path"
