#!/usr/bin/env bash

if [ -z "$1" ]; then
    echo "Usage: $0 <url>"
    exit 1
fi
# Possible URL schemes:
# git@github.com:Lerrrtaste/scripts.git -> ~/repos/github.com/Lerrrtaste/scripts
# https://github.com/Lerrrtaste/scripts.git -> ~/repos/github.com/Lerrrtaste/scripts
# https://git.concat.de/Lerrrtaste/scripts.git -> ~/repos/git.concat.de/Lerrrtaste/scripts
# git@git.concat.de/Lerrrtaste/scripts.git -> ~/repos/git.concat.de/Lerrrtaste/scripts
url="$1"
if [[ "$url" == *"git@"* ]]; then
    base_url="$(cut -d'@' -f2 <<< "$url")"
    domain="$(cut -d':' -f1 <<< "$base_url")"
    user="$(cut -d':' -f2 <<< "$base_url")"
else
    base_url="$(cut -d'/' -f3- <<< "$url")"
    domain="$(cut -d'/' -f1 <<< "$base_url")"
    user="$(cut -d'/' -f2 <<< "$base_url")"
fi
path="$HOME/repos/$domain/$user/$repo"
path="$(echo "$path" | tr '[:upper:]' '[:lower:]')"
echo "Cloning $url to $path"
if [ -e "$path" ]; then
    echo "Path $path already exists"
    exit 1
fi
git clone "$url" "$path"
